import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } from "docx";
import { jsPDF } from "jspdf";
import type { TranscriptResult } from "./yt-dlp";

// ---------------------------------------------------------------------------
// Markdown
// ---------------------------------------------------------------------------

export function generateMarkdown(
  results: TranscriptResult[],
  sourceLabel: string
): string {
  const timestamp = new Date().toISOString().slice(0, 19).replace("T", " ");
  const successful = results.filter((r) => r.transcript);
  const failed = results.filter((r) => !r.transcript);

  let md = `# YouTube Transcript Export\n\n`;
  md += `**Source:** ${sourceLabel}\n`;
  md += `**Exported:** ${timestamp}\n`;
  md += `**Videos:** ${results.length} total, ${successful.length} transcribed, ${failed.length} skipped\n\n`;
  md += `---\n\n`;

  for (const r of results) {
    md += `## ${r.title}\n\n`;
    md += `**URL:** ${r.url}\n\n`;

    if (r.transcript) {
      md += `${r.transcript}\n\n`;
    } else {
      md += `*No transcript available${r.error ? ` (${r.error})` : ""}*\n\n`;
    }
    md += `---\n\n`;
  }

  md += `\n*Generated by YT Transcript Extractor -- Built by Christopher Gentile / NewDawn AI*\n`;
  return md;
}

// ---------------------------------------------------------------------------
// PDF
// ---------------------------------------------------------------------------

export function generatePdf(
  results: TranscriptResult[],
  sourceLabel: string
): Buffer {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 15;
  const maxWidth = pageWidth - margin * 2;
  let y = margin;

  const timestamp = new Date().toISOString().slice(0, 19).replace("T", " ");
  const successful = results.filter((r) => r.transcript);
  const failed = results.filter((r) => !r.transcript);

  function checkPage(neededHeight: number) {
    if (y + neededHeight > doc.internal.pageSize.getHeight() - margin) {
      doc.addPage();
      y = margin;
    }
  }

  // Title
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text("YouTube Transcript Export", margin, y);
  y += 10;

  // Meta
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 100);
  doc.text(`Source: ${sourceLabel}`, margin, y);
  y += 5;
  doc.text(`Exported: ${timestamp}`, margin, y);
  y += 5;
  doc.text(
    `Videos: ${results.length} total, ${successful.length} transcribed, ${failed.length} skipped`,
    margin,
    y
  );
  y += 8;
  doc.setTextColor(0, 0, 0);

  // Separator
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, y, pageWidth - margin, y);
  y += 8;

  for (const r of results) {
    checkPage(20);

    // Video title
    doc.setFontSize(13);
    doc.setFont("helvetica", "bold");
    const titleLines = doc.splitTextToSize(r.title, maxWidth) as string[];
    doc.text(titleLines, margin, y);
    y += titleLines.length * 6 + 2;

    // URL
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(50, 100, 200);
    doc.text(r.url, margin, y);
    y += 6;
    doc.setTextColor(0, 0, 0);

    if (r.transcript) {
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      const textLines = doc.splitTextToSize(r.transcript, maxWidth) as string[];

      for (const line of textLines) {
        checkPage(5);
        doc.text(line, margin, y);
        y += 4.5;
      }
    } else {
      doc.setFontSize(10);
      doc.setFont("helvetica", "italic");
      doc.setTextColor(150, 150, 150);
      doc.text(`No transcript available${r.error ? ` (${r.error})` : ""}`, margin, y);
      y += 5;
      doc.setTextColor(0, 0, 0);
    }

    y += 4;
    checkPage(2);
    doc.setDrawColor(220, 220, 220);
    doc.line(margin, y, pageWidth - margin, y);
    y += 8;
  }

  // Footer
  checkPage(10);
  doc.setFontSize(8);
  doc.setTextColor(130, 130, 130);
  doc.text(
    "Generated by YT Transcript Extractor -- Built by Christopher Gentile / NewDawn AI",
    margin,
    doc.internal.pageSize.getHeight() - 8
  );

  return Buffer.from(doc.output("arraybuffer"));
}

// ---------------------------------------------------------------------------
// DOCX
// ---------------------------------------------------------------------------

export async function generateDocx(
  results: TranscriptResult[],
  sourceLabel: string
): Promise<Buffer> {
  const timestamp = new Date().toISOString().slice(0, 19).replace("T", " ");
  const successful = results.filter((r) => r.transcript);
  const failed = results.filter((r) => !r.transcript);

  const children: Paragraph[] = [];

  // Title
  children.push(
    new Paragraph({
      text: "YouTube Transcript Export",
      heading: HeadingLevel.TITLE,
      spacing: { after: 200 },
    })
  );

  // Meta
  children.push(
    new Paragraph({
      children: [
        new TextRun({ text: "Source: ", bold: true, size: 20 }),
        new TextRun({ text: sourceLabel, size: 20 }),
      ],
    })
  );
  children.push(
    new Paragraph({
      children: [
        new TextRun({ text: "Exported: ", bold: true, size: 20 }),
        new TextRun({ text: timestamp, size: 20 }),
      ],
    })
  );
  children.push(
    new Paragraph({
      children: [
        new TextRun({ text: "Videos: ", bold: true, size: 20 }),
        new TextRun({
          text: `${results.length} total, ${successful.length} transcribed, ${failed.length} skipped`,
          size: 20,
        }),
      ],
      spacing: { after: 300 },
    })
  );

  for (const r of results) {
    // Video title
    children.push(
      new Paragraph({
        text: r.title,
        heading: HeadingLevel.HEADING_2,
        spacing: { before: 300, after: 100 },
      })
    );

    // URL
    children.push(
      new Paragraph({
        children: [
          new TextRun({
            text: r.url,
            color: "3264C8",
            size: 18,
          }),
        ],
        spacing: { after: 150 },
      })
    );

    if (r.transcript) {
      // Split into paragraphs to avoid extremely long runs
      const paragraphs = splitIntoParagraphs(r.transcript, 2000);
      for (const p of paragraphs) {
        children.push(
          new Paragraph({
            children: [new TextRun({ text: p, size: 22 })],
            spacing: { after: 80 },
          })
        );
      }
    } else {
      children.push(
        new Paragraph({
          children: [
            new TextRun({
              text: `No transcript available${r.error ? ` (${r.error})` : ""}`,
              italics: true,
              color: "999999",
              size: 22,
            }),
          ],
        })
      );
    }

    // Separator
    children.push(
      new Paragraph({
        children: [
          new TextRun({
            text: "________________________________________",
            color: "DDDDDD",
            size: 16,
          }),
        ],
        alignment: AlignmentType.CENTER,
        spacing: { before: 200, after: 200 },
      })
    );
  }

  // Footer
  children.push(
    new Paragraph({
      children: [
        new TextRun({
          text: "Generated by YT Transcript Extractor -- Built by Christopher Gentile / NewDawn AI",
          italics: true,
          color: "999999",
          size: 16,
        }),
      ],
      spacing: { before: 400 },
      alignment: AlignmentType.CENTER,
    })
  );

  const doc = new Document({
    sections: [{ children }],
  });

  const buffer = await Packer.toBuffer(doc);
  return Buffer.from(buffer);
}

function splitIntoParagraphs(text: string, maxLen: number): string[] {
  if (text.length <= maxLen) return [text];

  const result: string[] = [];
  let remaining = text;

  while (remaining.length > maxLen) {
    let splitAt = remaining.lastIndexOf(". ", maxLen);
    if (splitAt === -1 || splitAt < maxLen / 2) {
      splitAt = remaining.lastIndexOf(" ", maxLen);
    }
    if (splitAt === -1) {
      splitAt = maxLen;
    }
    result.push(remaining.substring(0, splitAt + 1).trim());
    remaining = remaining.substring(splitAt + 1).trim();
  }

  if (remaining) result.push(remaining);
  return result;
}
